### ISSUE TITLE
InventoryExhaustedException

### ISSUE THREAD

**Issue by drewburlingame** [gbValant/Inventory#4]
I noticed you have 3 ctors on InventoryExhaustedException, but only the default ctor is every used.  Are there any benefits to having the other two ctors?  Any cons?

**Comment by gbValant** [comment]
The cons are that I have unused code, the pro is that it matches the expected base ctors of the class from which it was derived and makes the pass through to the base implementation explicit. 

To be honest, I can't recall off the top of my head if the base implementations would be automatically exposed in this case. I'm pretty sure they would. The one thing I would definitely not want to do is break the base and violate Liskov.
