### ISSUE TITLE
InventoryProvider.RemoveItem

### ISSUE THREAD

**Issue by drewburlingame** [gbValant/Inventory#6]
if (itemStore.TryGetValue(label, out currentInventoryItem) && itemStore[label].ItemCount > 0)
            {
                itemStore[label].Decrement();
                _notificationProvider.SendNotification(new Notification() { Item = currentInventoryItem.Item, Type = Notification.NotificationTypes.ItemRemoved });
            }

what's the pro/con of referencing itemStore[label] instead of currentInventoryItem in this block?

**Comment by gbValant** [comment]
The pro is that if the state changed somehow between TryGet and checking the count, I should get a current value and I should act against the actual current value (I think, I would definitely want to do a deeper dive on concurrentDictionary for this segment given the opportunity).

The big con is that I could theoretically in an edge case act on a value of 0 with my Decrement and there is no protection against going below 0 in the current Decrement method. As mentioned in the readme, properly engaging the complexities of TryUpdate with protections in the expression for the update case and using currentInventoryItem as the "expected state" would be the more fool proof approach to this.
